### PR TITLE
Shorten BGP filter

### LINKED ISSUE #199: BGP filter is too wide
It contains private addresses of other partitions with /32 notation.
This yields in utterly long FRR route-maps.

### PR DESCRIPTION
**Pull request by mwindower**
fixes #199 

TODO:

- [ ] test with DMZ and Storage Setup in Test Env

### CODE REVIEW

**Comment by mwindower** [comment]
TODO: DMZ setup has to be considered

**Review by mwennrich — APPROVED** [review]

**Comment by majst01** [comment]
This is not a fix, it just tries to shorten the route-maps in place and reduce therefore the probability for long running reloads which in turn sometimes lead to lost routes. The real fix is adding this fix to frr-reload.py on the leafs: https://github.com/FRRouting/frr/commit/6293c2181a3c58046f94496391d14a921a7fd892

**Comment by majst01** [comment]
We should keep this PR open for reference, i still think its useful, we should discuss and test this at a later stage

**Comment by majst01** [comment]
Simpler implementation was found with #559

**Pull request closed without merging**
