### PR TITLE
Update to go 1.15 in module, use alpine 3.12, remove redoc serve path

### PR DESCRIPTION
**Pull request by majst01**
@droid42 our image from where we got the redoc-cli was not modified/updated since years, created a redoc-cli installation stage directly. How can we access the redoc gui  and see what changed ?

### CODE REVIEW

**Comment by majst01** [comment]
Should we move the redoc generated swagger documentation move to the docs project ?
Votes ?

**Comment by Gerrit91** [comment]
Mh, personally, I don't really think the redoc endpoint is necessary and I have never met someone who used it. To me it's just an increase of the API's attack surface. I do provide the redoc documentation already for every metal-stack release.

**Review by Gerrit91 — APPROVED** [review]

**Comment by majst01** [comment]
But where is the redoc documentation ?

**Comment by Gerrit91** [comment]
https://docs.metal-stack.io/stable/apidocs/apidocs/

**Comment by majst01** [comment]
OK, perfect, so i will remove the apidocs from the metal-api container.

**Pull request merged**
