### PR TITLE
Update go-ipam

### PR DESCRIPTION
**Pull request by majst01**
which had a small API change, interface instead of struct, constants for sslmodes

### CODE REVIEW

**Comment by majst01** [comment]
Tested right now in test control-plane, all pods get OOMKilled ???

**Comment by majst01** [comment]
Error from mini-lab:

```
k logs metal-api-5fc84b886f-2p5ww
{"level":"info","time":"2020-05-27T12:24:40.737Z","caller":"metal-api/main.go:225","message":"starting metrics endpoint"}
{"level":"info","time":"2020-05-27T12:24:40.757Z","caller":"datastore/rethinkdb.go:166","message":"Rethinkstore connected"}
{"level":"info","time":"2020-05-27T12:24:40.782Z","caller":"eventbus/nsq.go:44","message":"nsq connected","nsqd":"&{TCPAddress:192.168.121.1.xip.io:4150 HTTPEndpoint:nsqd:4151 TLS:0xc00000cca0 NSQ:0xc000536640}"}
{"level":"info","time":"2020-05-27T12:24:40.783Z","caller":"eventbus/nsq.go:79","message":"topic created","partition":"vagrant","topic":"vagrant-machine"}
{"level":"info","time":"2020-05-27T12:24:40.786Z","caller":"metal-api/main.go:397","message":"ipam initialized"}
{"level":"info","time":"2020-05-27T12:24:40.849Z","caller":"metal-api/main.go:370","message":"masterdata client initialized"}
{"level":"fatal","time":"2020-05-27T12:24:41.027Z","caller":"metal-api/main.go:409","message":"dex not reachable","error":"cannot fetch dex keys from None/keys: invalid url scheme "}

```

**Comment by Gerrit91** [comment]
The mini-lab error regarding dex is resolved since metal-roles v0.1.12.

**Comment by majst01** [comment]
Tested in Test, merge now

**Pull request merged**
