### PR TITLE
Introduce allocation roles.

### PR DESCRIPTION
**Pull request by Gerrit91**
Closes https://github.com/metal-stack/metal-api/issues/24

### CODE REVIEW

**Comment by Gerrit91** [comment]
Tried successfully in the mini-lab.

**Review by majst01 — APPROVED** [review]
Should we add constants in metal-lib for these 2 new introduced roles ?

**Comment by Gerrit91** [comment]
In metal-lib? What do you mean?

**Comment by majst01** [comment]
I mean for consumers of metal-go to be able to use this feature as well instead of comparing strings

**Comment by Gerrit91** [comment]
I got you now. I added `enum` definitions to the swagger spec, such that the generated client now contains constants for the types as well.

**Comment by majst01** [comment]
Glad to see the `enum` feature works now in swagger spec generation, we have plenty of other places where this would be very useful

**Comment by Gerrit91** [comment]
I think this explicit annotation works since a long time, we already have it in many places. But automatic detection does not work for some reason. :/

**Comment by majst01** [comment]
Migration must be tested in real world also

**Pull request merged**
